spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:postgresql://${POSTGRESQL_HOST}:${POSTGRESQL_PORT}/postgres
    username: ${POSTGRESQL_ID}
    password: ${POSTGRESQL_PASS}
    driver-class-name: org.postgresql.Driver
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      username: ${REDIS_USERNAME}
      password: ${REDIS_PASSWORD}

eureka:
  client:
    register-with-eureka: true  # Eureka 서버에 등록
    fetch-registry: true        # Eureka 서버로부터 서비스 조회
    service-url:
      defaultZone: http://${EUREKA_HOST}:${EUREKA_PORT}/eureka/

server:
  host: ${SERVER_HOST}

logging:
  level:
    org.springframework: ${DEBUG_MODE}