server:
  port: 18081

spring:
  application:
    name: user-server
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  data:
    redis:
      host: localhost
      port: 6379
      username: default
      password: systempass

# jwt
jwt:
  secret:
    key: 09f001b9896c05dc6d2c353da804aa7e5d14622943889409dce157a8793af945067b8f07570c97529e1bed70ee339398c3fb576ba4547e2162ab9ea9aa365483

springdoc:
  swagger-ui:
    path: /user-server/swagger-ui
  api-docs:
    path: /user-server/v3/api-docs