spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:postgresql://${POSTGRESQL_HOST}:${POSTGRESQL_PORT}/postgres
    username: ${POSTGRESQL_ID}
    password: ${POSTGRESQL_PASS}
    driver-class-name: org.postgresql.Driver
  kafka:
    bootstrap-servers: ${server.host}:9092
  # S3 사용을 위한 설정
  cloud:
    aws:
      credentials:
        access-key: ${AWS_ACCESSKEY}
        secret-key: ${AWS_SECRETKEY}
      region:
        static: ${AWS_REGION}
      s3:
        bucket-name: ${AWS_S3_BUCKETNAME}

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST}:${EUREKA_PORT}/eureka/

server:
  host: ${SERVER_HOST}