spring:
  config:
    activate:
      on-profile: dev

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
data:
  redis:
    username: default
    password: systempass
