spring:
  profiles:
    default: dev
  application:
    name: queue-server

  # Redis만 사용
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

server:
  port: 18084

springdoc:
  swagger-ui:
    path: /queue-server/swagger-ui
  api-docs:
    path: /queue-server/v3/api-

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true

  scheduler:
    enabled: true