spring:
  config:
    activate:
      on-profile: test

  data:
    redis:
      host: 127.0.0.1
      port: 63790

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
