spring:
  config:
    activate:
      on-profile: prod

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST}:${EUREKA_PORT}/eureka/

data:
  redis:
    username: ${REDIS_USERNAME}
    password: ${REDIS_PASSWORD}