spring:
  profiles:
    default: dev
  application:
    name: eureka-server

server:
  port: 8761

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true
